[[main]]
name = 'Estudos'
pageRef = '/estudos'
weight = 10

[[main]]
name = 'Projetos'
pageRef = '/projetos'
weight = 20

[[main]]
name = 'Aprendizados'
pageRef = '/aprendizados'
weight = 30

[[main]]
name = 'Pessoal'
pageRef = '/pessoal'
weight = 40

[[main]]
name = 'In Memoriam'
pageRef = '/in-memoriam'
weight = 50

[[main]]
name = 'Sobre'
pageRef = '/sobre'
weight = 60
